### ISSUE TITLE
Display items duping on restart

### ISSUE THREAD

**Issue by csorrows** [RegalOwl/HyperConomy#55] opened 2015-01-03 03:15 UTC
I'm using a bunch of item displays in my shop. Upon server restarts, some of the items are duped allowing players to pickup the extra ones. Wierd thing is, it only happens to some not all.

HyperConomy:  v0.975.2 [Dev]
Spigot: git-Spigot-52c130f-89944c0

**Comment by RegalOwl** [comment] 2015-01-05 03:21
How many duplicates are made?  1 or many?  Is this from a /reload command or a full server restart?  What are some items that are duplicated?

**Comment by csorrows** [comment] 2015-01-05 03:46
1 duplicate is made. Some of them actually join with the original display and are protected. I have not tried with a /reload as I do not like using it. This is with a full restart. I have it disabled now for obvious reasons but I remember discs, tools, and redstone items being duped.

**Comment by RegalOwl** [comment] 2015-01-06 05:24
Not able to reproduce this so far.  Does it happen consistently every restart?  Maybe only when no one is online?  Have any other plugins which might be conflicting?   Let me know if you find a pattern.

**Comment by csorrows** [comment] 2015-01-06 09:12
Everytime. As I said, I have disabled it. When I get some spare time I will do some testing.

**Comment by RegalOwl** [comment] 2015-01-08 19:04
What other plugins are you running?  I've got another person reporting the same issue.  It may be a plugin conflict so finding overlapping plugins may help.

**Comment by csorrows** [comment] 2015-01-09 01:22
5:24:14 PM
 CONSOLE:
[INFO] Plugins (25): WorldBorder, ServerCaptcha, WorldEdit, WorldGuardFix, BukkitCompat, Vault, PermissionsEx, HostHordeHealth, ProtocolLib, HolographicDisplays, RandomTP, BedHome, WorldGuard, MobMoney, HomeSpawnPlus, Essentials, HyperConomy, Citizens, TouchscreenHolograms, HyperMerchant, NoCheatPlus, Sentry, VanishNoPacket, ColoredTags, EssentialsChat

**Comment by csorrows** [comment] 2015-01-09 02:12
Only ones I can think that could have anything to do with it would be NCP or maybe the WorldGuardFix patch. Possibly a 1.8 incompatibility of WG that the patch missed? Atleast I do not have a bunch of item modifying plugins.

**Comment by RegalOwl** [comment] 2015-01-13 04:55
I've tried most of the plugins and still can't reproduce it.  If you have time could you see if the same thing happens on your server (or test server) without other plugins?  I could potentially make you a test build as well which prints debug information to figure out what's going on.

**Comment by RegalOwl** [comment] 2015-02-07 05:46
Closing this for now.  Please make a new ticket if this is still a problem.  Haven't been able to reproduce this.

**Closed by RegalOwl** 2015-02-07 05:46 UTC
Labels: Can't Reproduce
